feat(cicd): adding report-coverage

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -1,25 +1,35 @@
 on: push
 name: Main
 jobs:
-  selectMasterBranch:
-    name: Select master branch
+  lint-test:
+    name: Lint and Test
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@master
-    - name: Select master branch
-      uses: actions/bin/filter@master
-      with:
-        args: branch master
-    - name: Install dependencies
-      uses: actions/npm@master
-      with:
-        entrypoint: yarn
-        args: install
-    - name: Prebuild libraries
-      uses: actions/npm@master
-      with:
-        args: run prebuild
-    - name: Test
-      uses: actions/npm@master
-      with:
-        args: run test
+      - uses: actions/checkout@v1
+      - name: Use Node.js 12.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+      # - name: Install YARN
+      #   run: npm install -g yarn
+      - name: Setup Angular CLI
+        run: yarn global add @angular/cli
+      - name: Install Dependencies
+        run: yarn install
+      - name: Linting
+        run: ng lint ngx-utils
+      - name: Testing
+        run: ng test ngx-utils
+      - name: Upload coverage to Codecov
+        run: bash <(curl -s https://codecov.io/bash)
+          -F unittests
+          -n codecov-ngx
+          -f ./coverage/libs/ngx-utils/coverage-final.json
+          -B ${{ github.head_ref }}
+          -C ${{ github.event.after }}
+          -P ${{ github.event.number }}
+          -Z || echo 'Codecov upload failed'
+        env:
+          CI: true
+          CODECOV_ENV: github-action
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
